// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestETL.Infrastructure.Db;

#nullable disable

namespace TestETL.Infrastructure.Migrations
{
    [DbContext(typeof(EtldbContext))]
    [Migration("20250108214732_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestETL.Domain.Models.Csv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DolocationId")
                        .HasColumnType("int")
                        .HasColumnName("DOLocationID");

                    b.Property<decimal?>("FareAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("fare_amount");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int")
                        .HasColumnName("passenger_count");

                    b.Property<int>("PulocationId")
                        .HasColumnType("int")
                        .HasColumnName("PULocationID");

                    b.Property<string>("StoreAndFwdFlag")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("store_and_fwd_flag");

                    b.Property<decimal?>("TipAmount")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("tip_amount");

                    b.Property<DateTime>("TpepDropoffDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("tpep_dropoff_datetime");

                    b.Property<DateTime>("TpepPickupDatetime")
                        .HasColumnType("datetime")
                        .HasColumnName("tpep_pickup_datetime");

                    b.Property<decimal?>("TripDistance")
                        .HasColumnType("numeric(5, 3)")
                        .HasColumnName("trip_distance");

                    b.HasKey("Id")
                        .HasName("PK_CSVId");

                    b.HasIndex(new[] { "PulocationId" }, "IX_PULocationID");

                    b.HasIndex(new[] { "TpepDropoffDatetime" }, "IX_tpep_dropoff_datetime");

                    b.HasIndex(new[] { "TripDistance" }, "IX_trip_distance");

                    b.ToTable("CSV", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
